require:
  - rubocop-rails
  - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: true
  CountRepeatedAttributes: false